config/routes.rb
Rails.application.routes.draw do
  get 'info/alcaldia'

  get 'info/index'

  get 'info/info'

  get 'autenticar/aut'

  get 'autenticar/out'

  get 'autenticar/salu'

  get 'sesiones/entrar'

  get 'sesiones/hola'

  get 'sesiones/salir'

  get 'buscar/form'

  get 'buscar/mosa'

  get 'buscar/show'

  resources :sesiones
  get 'login' => 'sesiones#entrar', :as => :login
  get 'saludo' => 'sesiones#hola', :as => :saludo
  resources :autenticar
  get 'ingreso' => 'autenticar#aut', :as => :ingreso
  get 'binve' => 'autenticar#salu', :as => :binve

  resources :personas

  resources :grupos

  resources :otras

  resources :locates

  root 'welcome#index'
   post ':controller(/:action(/:id))'

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
	has_many :personas
	has_one :otra
	belongs_to :locate
	attr_accessible :famil, :dir, :tel, :tipcasa, :estrato, :serv, :tipserv, :habit, :picasa, :murcasa, :basura, :eqcoc, :eqsal, :eqhabi, :eqcom, :locate_id
	validates :famil, presence: {message:"campo obligatorio"}
	validates :dir, presence: {message:"campo obligatorio"}
	validates :tel, presence: {message:"campo obligatorio"}
	validates :tipcasa, presence: {message:"campo obligatorio"}
	validates :estrato, presence: {message:"campo obligatorio"}
	validates :tipserv, presence: {message:"campo obligatorio"}
	validates :habit, presence: {message:"campo obligatorio"}
	validates :picasa, presence: {message:"campo obligatorio"}
	validates :murcasa, presence: {message:"campo obligatorio"}
	validates :basura, presence: {message:"campo obligatorio"}
	validates :eqcoc, presence: {message:"campo obligatorio"}
	validates :eqsal, presence: {message:"campo obligatorio"}
	validates :eqhabi, presence: {message:"campo obligatorio"}
	validates :eqcom, presence: {message:"campo obligatorio"}
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
   before_action :set_grupo, only: [:show, :edit, :update, :destroy]
   before_filter :chekear, :only => :new
  # GET /grupos
  # GET /grupos.json
  layout :resolve_layout
  def index
    @grupos = Grupo.all
  end

  # GET /grupos/1
  # GET /grupos/1.json
  def show
    #$ides =  Grupo.maximum('id')
    
    #if @ides
       #cookies[:id] = @ides
      #redirect_to new_persona_path 
    #end
  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
    
  end

  # GET /grupos/1/edit
  def edit
  end

  # POST /grupos
  # POST /grupos.json
  def create
    @grupo = Grupo.new(grupo_params)

    respond_to do |format|
      if @grupo.save
        $ides =  Grupo.maximum('id')
        #format.html { redirect_to @otra ,notice: 'Bloque anterior guardado' }
        format.html { redirect_to :controller => 'otras', :action => 'new', :id => @otra   }
        #format.html { redirect_to @grupo, notice: 'Grupo was successfully created.' }
        #format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos/1
  # PATCH/PUT /grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: 'Grupo was successfully updated.' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to grupos_url, notice: 'Grupo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:famil, :dir, :tel, :tipcasa, :estrato, :serv, :tipserv, :habit, :picasa, :murcasa, :basura, :eqcoc, :eqsal, :eqhabi, :eqcom,:locate_id)
    end
    def chekear
      if  $administration 
        redirect_to :controller => "sesiones", :action => "entrar", :alert => "Primero logueese para llenar la encuesta."
      end

    end
    
    def resolve_layout
    case action_name
    when "index"
      "tab"
    when "new","edit","create","show"
      "boots"
    end
   end 
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/_form.html.erb
<%= form_for(@grupo) do |f| %>
  <% if @grupo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupo.errors.count, "error") %> prohibited this grupo from being saved:</h2>

      <ul>
      <% @grupo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h3></h3>
  <div class="col-xs-5 center-block" style="float:none"> 
  <div class="form-group">
  <%= f.text_field :famil,class:"span3",placeholder:".Apellidos Familia" %>
     
    <%= f.text_field :dir, class:"span4",placeholder:".Direccion" %>  
     
    <%= f.text_field :tel, placeholder:".telefono" %> 
    <% viviendas = {'Vivienda_tipo' =>'Vivienda_tipo', 'casa' => 'casa','apartamento' =>'apartamento','casa lote' =>'casa lote','finca'=>'finca'} %>
    <% lista = viviendas.sort %>
     <%= f.select :tipcasa, lista, :selected => '.Vivienda_tipo' %> 
     
        <%= f.text_field :estrato, class:"span2",placeholder:".Estrato?" %>
  </div>
    
  
 <%= f.label :Tiene_servicios_incluidos? %>
    <%= f.check_box :serv %>
  
    <%= f.label :Cuales? %>
    <%= f.text_area :tipserv, :cols =>100, rows: 4 %><br> 
  <div class="form-group">
    <%= f.text_field :habit, placeholder:" # de habitaciones" %>
    <% pisos = {'Tipo de Pisos' =>'Tipo de Pisos', 'Tierra,Arena' => 'Tierra,Arena','Cemento,gravilla' =>'Cemento,gravilla','Madera' =>'Madera ','Baldosa'=>'Baldosa'} %>
    <% pis = pisos.sort %>
    <%= f.select :picasa,pis,:selected =>'Tipo de Pisos' %> 
    <% pared = {'Tipo de Paredes' =>'Tipo de Paredes', 'Ladrillo' => 'Ladrillo','Madera' =>'Madera','Adobe,Bahareque' =>'Adobe,Bahareque ','Guadua'=>'Guadua','Zinc'=>'Zinc'} %>
    <% par = pared.sort %>
    <%= f.select :murcasa,par,:selected => 'Tipo de Paredes' %>
 <% basura = {'Control de Basuras' =>'Control de Basuras', 'Reciclan' => 'Reciclan','Recoleccion Publica' =>'Recoleccion Publica','Se arroja a un rio o Quebrada' =>'Se arroja a un rio o Quebrada ','Se Quema'=>'Se Quema'} %>
    <% bas = basura.sort %>
    
    <%= f.select :basura,bas,:selected => 'Control de Basuras' %>
  <% cocin = {'Equipos de Cocina' =>'Equipos de Cocina', 'Completo' => 'Completo','Incompleto' =>'Incompleto'} %>
    <% co = cocin.sort %> 
    <%= f.select :eqcoc, co,:selected => 'Equipos de Cocina'%> 
  </div>
  <div class="form-group">
    <% sala = {'Equipo de Sala' =>'Equipo de Sala', 'Completo' => 'Completo','Incompleto' =>'Incompleto'} %>
    <% sal = sala.sort %> 
    <%= f.select :eqsal, sal,:selected => 'Equipo de Sala'%> 
   <% habit = {'Equipo de Habitacion' =>'Equipo de Habitacion', 'Completo' => 'Completo','Incompleto' =>'Incompleto'} %>
    <% ht = habit.sort %> 
    <%= f.select :eqhabi,ht,:selected => 'Equipo de Habitacion' %>
  <% comed = {'Equipo de Comedor' =>'Equipo de Comedor', 'Completo' => 'Completo','Incompleto' =>'Incompleto'} %>
    <% cmd = comed.sort %> 
    
    <%= f.select :eqcom,cmd,:selected => 'Equipo de Comedor' %>
    <%= f.number_field :locate_id,:value => $locs, class:"span2" %>
  </div>
  <br>
     <%= f.submit "siguiente", class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/grupos/edit.html.erb
<h1>Editing grupo</h1>

<%= render 'form' %>

<%= link_to 'Show', @grupo %> |
<%= link_to 'Back', grupos_path %>

app/views/grupos/index.html.erb
<h1 class = "text-center">Entrada de Datos Por Grupo Familiar</h1>
<div class="CSSTableGenerator" >
<table>
  <thead>
    <tr>
      <th>Famil</th>
      <th>Integrantes</th>
      <th>Dir</th>
      <th>Tel</th>
      <th>Tipcasa</th>
      <th>Estrato</th>
      <th>Serv</th>
      <th>Tipserv</th>
      <th>Habit</th>
      <th>Picasa</th>
      <th>Murcasa</th>
      <th>Basura</th>
      <th>Eqcoc</th>
      <th>Eqsal</th>
      <th>Eqhabi</th>
      <th>Eqcom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupos.each do |grupo| %>
      <tr>
        <td><%= grupo.famil %></td>
        <td><%= grupo.personas.count %></td>
        <td><%= grupo.dir %></td>
        <td><%= grupo.tel %></td>
        <td><%= grupo.tipcasa %></td>
        <td><%= grupo.estrato %></td>
        <td><%= grupo.serv %></td>
        <td><%= grupo.tipserv %></td>
        <td><%= grupo.habit %></td>
        <td><%= grupo.picasa %></td>
        <td><%= grupo.murcasa %></td>
        <td><%= grupo.basura %></td>
        <td><%= grupo.eqcoc %></td>
        <td><%= grupo.eqsal %></td>
        <td><%= grupo.eqhabi %></td>
        <td><%= grupo.eqcom %></td>
        <td><%= link_to 'Show', grupo %></td>
        <td><%= link_to 'Edit', edit_grupo_path(grupo) %></td>
        <td><%= link_to 'Destroy', grupo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Grupo', new_grupo_path %>

app/views/grupos/new.html.erb
<div class="span12">
   	<div class="col-xs-5 center-block" style="float:none"> 
    <h1 class = "text-center"><a >INFORMACION DIAGNOSTICO CARTOGRAFIA SOCIAL</a></h1>
      <p class = "text-center" >DATOS GRUPO FAMILIAR</p>
     </div>
       
    <div class="span12">
     <img src="http://lorempixel.com/1190/200/nature" alt="">
    </div>
<div class="col">
<div class="span12">
<%= render 'form' %>
</div>
<%= link_to 'Back', grupos_path %>
</div>
</div>

app/views/grupos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Famil:</strong>
  <%= @grupo.famil %>
</p>

<p>
  <strong>Dir:</strong>
  <%= @grupo.dir %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @grupo.tel %>
</p>

<p>
  <strong>Tipcasa:</strong>
  <%= @grupo.tipcasa %>
</p>

<p>
  <strong>Estrato:</strong>
  <%= @grupo.estrato %>
</p>

<p>
  <strong>Serv:</strong>
  <%= @grupo.serv %>
</p>

<p>
  <strong>Tipserv:</strong>
  <%= @grupo.tipserv %>
</p>

<p>
  <strong>Habit:</strong>
  <%= @grupo.habit %>
</p>

<p>
  <strong>Picasa:</strong>
  <%= @grupo.picasa %>
</p>

<p>
  <strong>Murcasa:</strong>
  <%= @grupo.murcasa %>
</p>

<p>
  <strong>Basura:</strong>
  <%= @grupo.basura %>
</p>

<p>
  <strong>Eqcoc:</strong>
  <%= @grupo.eqcoc %>
</p>

<p>
  <strong>Eqsal:</strong>
  <%= @grupo.eqsal %>
</p>

<p>
  <strong>Eqhabi:</strong>
  <%= @grupo.eqhabi %>
</p>

<p>
  <strong>Eqcom:</strong>
  <%= @grupo.eqcom %>
</p>

<%= link_to 'Edit', edit_grupo_path(@grupo) %> |
<%= link_to 'Back', grupos_path %>