config/routes.rb
Rails.application.routes.draw do
  get 'info/alcaldia'

  get 'info/index'

  get 'info/info'

  get 'autenticar/aut'

  get 'autenticar/out'

  get 'autenticar/salu'

  get 'sesiones/entrar'

  get 'sesiones/hola'

  get 'sesiones/salir'

  get 'buscar/form'

  get 'buscar/mosa'

  get 'buscar/show'

  resources :sesiones
  get 'login' => 'sesiones#entrar', :as => :login
  get 'saludo' => 'sesiones#hola', :as => :saludo
  resources :autenticar
  get 'ingreso' => 'autenticar#aut', :as => :ingreso
  get 'binve' => 'autenticar#salu', :as => :binve

  resources :personas

  resources :grupos

  resources :otras

  resources :locates

  root 'welcome#index'
   post ':controller(/:action(/:id))'

end

app/models/otra.rb
class Otra < ActiveRecord::Base
	has_many :personas
	belongs_to :grupo
        belongs_to :locate
        attr_accessible :fuenteingre, :cualfuen, :cuentab, :numcuent, :tarjetdc, :cuantarj, :prestam, :tipoprestamo,:grupo_id,:locate_id
	#validates :fuenteingre, presence: {message:"campo obligatorio"}
	validates :cualfuen, presence: {message:"campo obligatorio"}
	#validates :cuentab,uniqueness:{message:"No puede estar Repetido"}, presence: {message:"campo obligatorio"}
	validates :numcuent, presence: {message:"campo obligatorio"}
	#validates :tarjetdc, presence: {message:"campo obligatorio"}
	validates :cuantarj, presence: {message:"campo obligatorio"}
	#validates :prestam, presence: {message:"campo obligatorio"}
	validates :tipoprestamo, presence: {message:"campo obligatorio"}
	validates :grupo_id, presence: {message:"campo obligatorio"}
end

app/controllers/otras_controller.rb
class OtrasController < ApplicationController
   before_filter :ver, only: [:new,:show,:edit] 
  # GET /personas
  # GET /personas.json
  layout :resolve_layout
  def index
    @otras = Otra.all
  end

  # GET /otras/1
  # GET /otras/1.json
  def show
  end

  # GET /otras/new
  def new
    @otra = Otra.new
  end

  # GET /otras/1/edit
  def edit
  end

  # POST /otras
  # POST /otras.json
  def create
    @otra = Otra.new(otra_params)

    respond_to do |format|
      if @otra.save
        format.html { redirect_to :controller => 'personas', :action => 'new', :id => @persona }
        #format.html { redirect_to @otra, notice: 'Otra was successfully created.' }
        #format.json { render :show, status: :created, location: @otra }
      else
        format.html { render :new }
        format.json { render json: @otra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /otras/1
  # PATCH/PUT /otras/1.json
  def update
    respond_to do |format|
      if @otra.update(otra_params)
        format.html { redirect_to @otra, notice: 'Otra was successfully updated.' }
        format.json { render :show, status: :ok, location: @otra }
      else
        format.html { render :edit }
        format.json { render json: @otra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /otras/1
  # DELETE /otras/1.json
  def destroy
    @otra.destroy
    respond_to do |format|
      format.html { redirect_to otras_url, notice: 'Otra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def ver
      if  $administration 
        redirect_to :controller => "sesiones", :action => "entrar", :alert => "Primero logueese para llenar la encuesta."
      end

    end
    def resolve_layout
    case action_name
    when "index"
      "tab"
    when "new","edit","show"
      "boots"
    end
   end 
    # Use callbacks to share common setup or constraints between actions.
    def set_otra
      @otra = Otra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def otra_params
      params.require(:otra).permit(:fuenteingre, :cualfuen, :cuentab, :numcuent, :tarjetdc, :cuantarj, :prestam, :tipoprestamo, :grupo_id, :locate_id)
    end
end

app/helpers/otras_helper.rb
module OtrasHelper
end

app/views/otras/_form.html.erb
<%= form_for(@otra) do |f| %>
  <% if @otra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@otra.errors.count, "error") %> prohibited this otra from being saved:</h2>

      <ul>
      <% @otra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h3></h3>
  <div class="col-xs-5 center-block" style="float:none"> 
  <div class="form-group">
    <% fute = {'Tipo De Ingresos Familiares' => 'Tipo De Ingresos Familiares', 'Agropecuearias' => 'Agropecuarias','Negocio Familiar' =>'Negocio Familiar','Empleado Privado' =>'Empleado Privado','Empleado Publico' =>'Empleado Publico','Trabajo Informal' =>'Trabajo Informal','Oficios Varios' => 'Oficios Varios', 'Desempleado' => 'Desempleado'} %>
    <% li = fute.sort %>
    <%= f.select :fuenteingre, li, :selected => 'Tipo De Ingresos Familiares' %>
    <%= f.text_field :cualfuen, class:"span4",placeholder:".Describa el Tipo de Ingresos" %>
  <%= f.label :Poseen_Cuentas_Bancarias? %>
    <%= f.check_box :cuentab %>
  <%= f.text_field :numcuent, class:"span3",placeholder:".Cuantas cuentas?" %>
  <%= f.label :Poseen_Tarjeta_Debito_o_Credito? %>
    <%= f.check_box :tarjetdc %>
   <%= f.text_field :cuantarj, class:"span3",placeholder:".cuantas tarjetas?" %>
  
  <%= f.label :Ha_hecho_Algun_Prestamo? %>
    <%= f.check_box :prestam %>
    <% pres = {'Tipo De Prestamo' =>'Tipo De Prestamo', 'Vivienda' => 'Vivienda','Libre Inversion' =>'Libre Inversion','Vehículo' =>'Vehículo','Ninguno'=>'Ninguno'} %>
    <% ptm = pres.sort %>
    <%= f.select :tipoprestamo, ptm, :selected => 'Tipo De Prestamo' %>
    <%= f.number_field :grupo_id,:value => $ides, class:"span2" %> 
    <%= f.number_field :locate_id,:value => $locs, class:"span2" %> 
 </div>
  <br>
     <%= f.submit "Entrar Datos", class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/otras/edit.html.erb
<h1>Editing otra</h1>

<%= render 'form' %>

<%= link_to 'Show', @otra %> |
<%= link_to 'Back', otras_path %>

app/views/otras/index.html.erb
<h1 class = "text-center">Otros Datos Familiares</h1>

<div class="CSSTableGenerator" >

<table>
  <thead>
    <tr>
      <th>Fuenteingre</th>
      <th>Cualfuen</th>
      <th>Cuentab</th>
      <th>Numcuent</th>
      <th>Tarjetdc</th>
      <th>Cuantarj</th>
      <th>Prestam</th>
      <th>Tipoprestamo</th>
      <th>Grupo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @otras.each do |otra| %>
      <tr>
        <td><%= otra.fuenteingre %></td>
        <td><%= otra.cualfuen %></td>
        <td><%= otra.cuentab %></td>
        <td><%= otra.numcuent %></td>
        <td><%= otra.tarjetdc %></td>
        <td><%= otra.cuantarj %></td>
        <td><%= otra.prestam %></td>
        <td><%= otra.tipoprestamo %></td>
        <td><%= otra.grupo_id %></td>
        <td><%= link_to 'Show', otra %></td>
        <td><%= link_to 'Edit', edit_otra_path(otra) %></td>
        <td><%= link_to 'Destroy', otra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Otra', new_otra_path %>

app/views/otras/new.html.erb
<div class="span12">
   	<div class="col-xs-5 center-block" style="float:none"> 
    <h1 class = "text-center"><a >OTROS DATOS DEL NUCLEO FAMILIAR</a></h1>
      <p class = "text-center" >CARTOGRAFIA SOCIAL MUNICIPAL</p>
     </div>
       
    <div class="span12">
     <img src="http://lorempixel.com/1190/200/nature" alt="">
    </div>
<div class="col">
<div class="span12">
  <%= render 'form' %>
  </div>

<%= link_to 'Back', otras_path %>
</div>
</div>

app/views/otras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fuenteingre:</strong>
  <%= @otra.fuenteingre %>
</p>

<p>
  <strong>Cualfuen:</strong>
  <%= @otra.cualfuen %>
</p>

<p>
  <strong>Cuentab:</strong>
  <%= @otra.cuentab %>
</p>

<p>
  <strong>Numcuent:</strong>
  <%= @otra.numcuent %>
</p>

<p>
  <strong>Tarjetdc:</strong>
  <%= @otra.tarjetdc %>
</p>

<p>
  <strong>Cuantarj:</strong>
  <%= @otra.cuantarj %>
</p>

<p>
  <strong>Prestam:</strong>
  <%= @otra.prestam %>
</p>

<p>
  <strong>Tipoprestamo:</strong>
  <%= @otra.tipoprestamo %>
</p>

<p>
  <strong>Grupo:</strong>
  <%= @otra.grupo_id %>
</p>

<%= link_to 'Edit', edit_otra_path(@otra) %> |
<%= link_to 'Back', otras_path %>