config/routes.rb
Rails.application.routes.draw do
  get 'info/alcaldia'

  get 'info/index'

  get 'info/info'

  get 'autenticar/aut'

  get 'autenticar/out'

  get 'autenticar/salu'

  get 'sesiones/entrar'

  get 'sesiones/hola'

  get 'sesiones/salir'

  get 'buscar/form'

  get 'buscar/mosa'

  get 'buscar/show'

  resources :sesiones
  get 'login' => 'sesiones#entrar', :as => :login
  get 'saludo' => 'sesiones#hola', :as => :saludo
  resources :autenticar
  get 'ingreso' => 'autenticar#aut', :as => :ingreso
  get 'binve' => 'autenticar#salu', :as => :binve

  resources :personas

  resources :grupos

  resources :otras

  resources :locates

  root 'welcome#index'
   post ':controller(/:action(/:id))'

end

app/models/persona.rb
class Persona < ActiveRecord::Base
        belongs_to :grupo
	belongs_to :otra
	belongs_to :locate
	        attr_accessible :nombre, :edad, :sexo, :cedula, :lugfam, :nivestu, :titul, :servsalud, :cajcomp, :pension, :etnia, :actiecom, :gruporel, :cualgrup, :sectortrab, :locate_id, :grupo_id, :otra_id
	
	validates :nombre,uniqueness:{message:"No puede estar Repetido"}, presence: {message:"campo obligatorio"}
	validates :edad, presence: {message:"campo obligatorio"}
	validates :cedula,uniqueness:{message:"No puede estar Repetido"}, presence: {message:"campo obligatorio"}
	validates :lugfam, presence: {message:"campo obligatorio"}
	validates :sexo, presence: {message:"campo obligatorio"}
	validates :nivestu, presence: {message:"campo obligatorio"}
	validates :titul, presence: {message:"campo obligatorio"}
	validates :servsalud, presence: {message:"campo obligatorio"}
	validates :cajcomp, presence: {message:"campo obligatorio"}
	validates :pension, presence: {message:"campo obligatorio"}
	validates :etnia, presence: {message:"campo obligatorio"}
	validates :actiecom, presence: {message:"campo obligatorio"}
	
	validates :cualgrup, presence: {message:"campo obligatorio"}
	validates :sectortrab, presence: {message:"campo obligatorio"}
	validates :grupo_id, presence: {message:"campo obligatorio"}
	validates :otra_id, presence: {message:"campo obligatorio"}
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]
  before_filter :ver, only: [:new,:show,:edit] 
  # GET /personas
  # GET /personas.json
  layout :resolve_layout
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
    if defined?(cookies[:id])
      @luc =  cookies[:id]

    end
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end
    
    def ver
      if  $administration 
        redirect_to :controller => "sesiones", :action => "entrar", :alert => "Primero logueese para llenar la encuesta."
      end

    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :edad, :sexo, :cedula, :lugfam, :nivestu, :titul, :servsalud, :cajcomp, :pension, :etnia, :actiecom, :gruporel, :cualgrup, :sectortrab,:locate_id, :grupo_id, :otra_id)
    end

    def resolve_layout
    case action_name
    when "index"
      "tab"
    when "new","edit","show"
      "boots"
    end
   end 
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h3></h3>
  <div class="col-xs-5 center-block" style="float:none"> 
  <div class="form-group">
 <%= f.text_field :nombre, class:"span4",placeholder:".Nombre Completo" %>  
  
     <%= f.label :Edad %>
    <%= f.number_field :edad, class:"span2",placeholder:".Edad" %>
    <% sexo = {'Sexo' =>'Sexo', 'Masculino' => 'Masculino','Femenino' =>'Femenino'} %>
    <% lista = sexo.sort %>
    <%= f.select :sexo, lista, :selected => 'Sexo' %>
 <%= f.text_field :cedula, class:"span2",placeholder:".Cedula" %>
      
    <%= f.text_field :lugfam, class:"span2",placeholder:".Lugar En la familia" %>
  </div>
  
  <div class="form-group">
   
    <%= f.text_field :nivestu, class:"span4",placeholder:".Estudios Realizados" %>
   <%= f.text_field :titul, class:"span3",placeholder:".Titulo Obtenido" %>
   <%= f.text_field :servsalud, class:"span2",placeholder:".Servicio De Salud" %>
   <%= f.text_field :cajcomp, class:"span2",placeholder:".Caja De Compensacion" %>
   <%= f.text_field :pension, class:"span2",placeholder:".Pensiones y Cesantias" %>
  </div>
  <%= f.text_field :etnia, class:"span2",placeholder:".Grupo Etnico" %>
   <%= f.text_field :actiecom, class:"span2",placeholder:".Actividad Economica" %>
  </div>
  <div class="form-group">
    <%= f.label :Grupos_Reconocidos_Por_la_Ley? %>
    <%= f.check_box :gruporel %>
    <%= f.text_field :cualgrup, class:"span2",placeholder:".Agregue el Grupo" %>
  
    <% active = {'Sectores' =>'Sectores', 'Agropecuario' => 'Agropecuario','Pesca' =>'Pesca','Industrial' =>'Industrial ','Servicios'=>'Servicios','Construccion'=>'Construccion','Mecanica'=>'Mecanica','Informatica'=>'Informatica','Educacion'=>'Educacion','ventas'=>'ventas','Otros'=>'Otros'} %>
    <% act = active.sort %>
    <%= f.label :En_que_sector_de_estos_le_gustaria_trabajar? %>
    <%= f.select :sectortrab,act, :selected => 'Sectores' %>
    <%= f.number_field :grupo_id,:value => $ides, class:"span2" %> 
    <%= f.number_field :otra_id,:value => $ides, class:"span2" %>
    <%= f.number_field :locate_id,:value => $locs, class:"span2" %>
  </div>
  <br>
     <%= f.submit "siguiente", class: "btn btn-primary"  %>
   

  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<h1 class = "text-center">Entrada de Datos Por Integrante De Familia</h1>

<div class="CSSTableGenerator" >
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Sexo</th>
      <th>Cedula</th>
      <th>Lugfam</th>
      <th>Nivestu</th>
      <th>Titul</th>
      <th>Servsalud</th>
      <th>Cajcomp</th>
      <th>Pension</th>
      <th>Etnia</th>
      <th>Actiecom</th>
      <th>Gruporel</th>
      <th>Cualgrup</th>
      <th>Sectortrab</th>
      <th>Grupo</th>
      <th>Otra</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.edad %></td>
        <td><%= persona.sexo %></td>
        <td><%= persona.cedula %></td>
        <td><%= persona.lugfam %></td>
        <td><%= persona.nivestu %></td>
        <td><%= persona.titul %></td>
        <td><%= persona.servsalud %></td>
        <td><%= persona.cajcomp %></td>
        <td><%= persona.pension %></td>
        <td><%= persona.etnia %></td>
        <td><%= persona.actiecom %></td>
        <td><%= persona.gruporel %></td>
        <td><%= persona.cualgrup %></td>
        <td><%= persona.sectortrab %></td>
        <td><%= persona.grupo_id %></td>
        <td><%= persona.otra_id %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<div class="span12">
   	<div class="col-xs-5 center-block" style="float:none"> 
    <h1 class = "text-center"><a >INFORMACION NUCLEO FAMILIAR</a></h1>
      <p class = "text-center" >Datos De Cada Miembro De la Familia</p>
     </div>
       
    <div class="span12">
     <img src="http://lorempixel.com/1190/200/nature" alt="">
    </div>
<div class="col">
<div class="span12">
  <%= render 'form' %>
</div>

<%= link_to 'Back', personas_path %>
</div>
</div>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @persona.edad %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @persona.sexo %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @persona.cedula %>
</p>

<p>
  <strong>Lugfam:</strong>
  <%= @persona.lugfam %>
</p>

<p>
  <strong>Nivestu:</strong>
  <%= @persona.nivestu %>
</p>

<p>
  <strong>Titul:</strong>
  <%= @persona.titul %>
</p>

<p>
  <strong>Servsalud:</strong>
  <%= @persona.servsalud %>
</p>

<p>
  <strong>Cajcomp:</strong>
  <%= @persona.cajcomp %>
</p>

<p>
  <strong>Pension:</strong>
  <%= @persona.pension %>
</p>

<p>
  <strong>Etnia:</strong>
  <%= @persona.etnia %>
</p>

<p>
  <strong>Actiecom:</strong>
  <%= @persona.actiecom %>
</p>

<p>
  <strong>Gruporel:</strong>
  <%= @persona.gruporel %>
</p>

<p>
  <strong>Cualgrup:</strong>
  <%= @persona.cualgrup %>
</p>

<p>
  <strong>Sectortrab:</strong>
  <%= @persona.sectortrab %>
</p>

<p>
  <strong>Grupo:</strong>
  <%= @persona.grupo_id %>
</p>

<p>
  <strong>Otra:</strong>
  <%= @persona.otra_id %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>