config/routes.rb
Rails.application.routes.draw do
  get 'info/alcaldia'

  get 'info/index'

  get 'info/info'

  get 'autenticar/aut'

  get 'autenticar/out'

  get 'autenticar/salu'

  get 'sesiones/entrar'

  get 'sesiones/hola'

  get 'sesiones/salir'

  get 'buscar/form'

  get 'buscar/mosa'

  get 'buscar/show'

  resources :sesiones
  get 'login' => 'sesiones#entrar', :as => :login
  get 'saludo' => 'sesiones#hola', :as => :saludo
  resources :autenticar
  get 'ingreso' => 'autenticar#aut', :as => :ingreso
  get 'binve' => 'autenticar#salu', :as => :binve

  resources :personas

  resources :grupos

  resources :otras

  resources :locates

  root 'welcome#index'
   post ':controller(/:action(/:id))'

end

app/models/locate.rb
class Locate < ActiveRecord::Base
   has_many :personas
   has_one :otra
   attr_accessible :departamento, :municipio, :gobernador, :alcalde, :fecha_inicio
   validates :departamento, presence: {message:"campo obligatorio"}
   validates :municipio, presence: {message:"campo obligatorio"}
   validates :gobernador, presence: {message:"campo obligatorio"}
   validates :alcalde, presence: {message:"campo obligatorio"}
end

app/controllers/locates_controller.rb
class LocatesController < ApplicationController
  before_action :set_locate, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout
  # GET /locates
  # GET /locates.json
  def index
    @locates = Locate.all
  end

  # GET /locates/1
  # GET /locates/1.json
  def show
  end

  # GET /locates/new
  def new
    @locate = Locate.new
  end

  # GET /locates/1/edit
  def edit
  end

  # POST /locates
  # POST /locates.json
  def create
    @locate = Locate.new(locate_params)
    $locs =  Locate.maximum('id')
    respond_to do |format|
      if @locate.save
        format.html { redirect_to :controller => 'grupos', :action => 'new', :id => @grupo   }
        #format.html { redirect_to @locate, notice: 'Locate was successfully created.' }
        #format.json { render :show, status: :created, location: @locate }
      else
        format.html { render :new }
        format.json { render json: @locate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locates/1
  # PATCH/PUT /locates/1.json
  def update
    respond_to do |format|
      if @locate.update(locate_params)
        format.html { redirect_to @locate, notice: 'Locate was successfully updated.' }
        format.json { render :show, status: :ok, location: @locate }
      else
        format.html { render :edit }
        format.json { render json: @locate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locates/1
  # DELETE /locates/1.json
  def destroy
    @locate.destroy
    respond_to do |format|
      format.html { redirect_to locates_url, notice: 'Locate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locate
      @locate = Locate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locate_params
      params.require(:locate).permit(:departamento, :municipio, :gobernador, :alcalde, :fecha_inicio)
    end
    def resolve_layout
    case action_name
    when "index"
      "tab"
    when "new","edit","show"
      "boots"
    end
   end 
end

app/helpers/locates_helper.rb
module LocatesHelper
end

app/views/locates/_form.html.erb
<%= form_for(@locate) do |f| %>
  <% if @locate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locate.errors.count, "error") %> prohibited this locate from being saved:</h2>

      <ul>
      <% @locate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3></h3>
  <div class="col-xs-5 center-block" style="float:none"> 
  <div class="form-group">
    <%= f.text_field :departamento, class:"span2",placeholder:".Departamento" %>
    <%= f.text_field :municipio, class:"span2",placeholder:".Municipio" %>
    
    <%= f.text_field :gobernador, class:"span2",placeholder:".Gobernador" %>
  
    <%= f.text_field :alcalde , class:"span2",placeholder:".Alcalde" %>
  </div>
  <div class="field">
    <%= f.label :fecha_inicio %>
    <%= f.date_select :fecha_inicio %>
  </div>
  <div class="actions">
    <%= f.submit "siguiente", class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/locates/edit.html.erb
<h1>Editing locate</h1>

<%= render 'form' %>

<%= link_to 'Show', @locate %> |
<%= link_to 'Back', locates_path %>

app/views/locates/index.html.erb
<h1 class = "text-center">Zonas Donde Se Realiza La Cartografia</h1>
<div class="CSSTableGenerator" >
<table>
  <thead>
    <tr>
      <th>Departamento</th>
      <th>Municipio</th>
      <th>Gobernador</th>
      <th>Alcalde</th>
      <th>Fecha inicio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locates.each do |locate| %>
      <tr>
        <td><%= locate.departamento %></td>
        <td><%= locate.municipio %></td>
        <td><%= locate.gobernador %></td>
        <td><%= locate.alcalde %></td>
        <td><%= locate.fecha_inicio %></td>
        <td><%= link_to 'Show', locate %></td>
        <td><%= link_to 'Edit', edit_locate_path(locate) %></td>
        <td><%= link_to 'Destroy', locate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Locate', new_locate_path %>

app/views/locates/new.html.erb
<div class="span12">
   	<div class="col-xs-5 center-block" style="float:none"> 
    <h1 class = "text-center"><a >DATOS DEL LUGAR GEOGRAFICO DE LA ENCUESTA</a></h1>
      <p class = "text-center" >CARTOGRAFIA SOCIAL MUNICIPAL</p>
     </div>
       
    <div class="span12">
     <img src="http://lorempixel.com/1190/200/nature" alt="">
    </div>
<div class="col">
<div class="span12">
  <%= render 'form' %>
  </div>


<%= link_to 'Back', locates_path %>
 </div>
 </div>

app/views/locates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departamento:</strong>
  <%= @locate.departamento %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @locate.municipio %>
</p>

<p>
  <strong>Gobernador:</strong>
  <%= @locate.gobernador %>
</p>

<p>
  <strong>Alcalde:</strong>
  <%= @locate.alcalde %>
</p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @locate.fecha_inicio %>
</p>

<%= link_to 'Edit', edit_locate_path(@locate) %> |
<%= link_to 'Back', locates_path %>